type Language = {
    id: number;
    lang_code: string;
    title: string;
};

export const LANGUAGES: Language[] = [
    { id: 1, lang_code: "aa", title: "Afaraf" },
    { id: 2, lang_code: "ab", title: "Аҧсуа" },
    { id: 3, lang_code: "ae", title: "Avesta" },
    { id: 4, lang_code: "af", title: "Afrikaans" },
    { id: 5, lang_code: "ak", title: "Akan" },
    { id: 6, lang_code: "am", title: "አማርኛ" },
    { id: 7, lang_code: "an", title: "Aragonés" },
    { id: 8, lang_code: "ar", title: "العربية" },
    { id: 9, lang_code: "as", title: "অসমীয়া" },
    { id: 10, lang_code: "av", title: "Авар мацӀ" },
    { id: 11, lang_code: "ay", title: "Aymar aru" },
    { id: 12, lang_code: "az", title: "Azərbaycan dili" },
    { id: 13, lang_code: "ba", title: "Башҡорт теле" },
    { id: 14, lang_code: "be", title: "Беларуская" },
    { id: 15, lang_code: "bg", title: "Български" },
    { id: 16, lang_code: "bh", title: "भोजपुरी" },
    { id: 17, lang_code: "bi", title: "Bislama" },
    { id: 18, lang_code: "bm", title: "Bamanankan" },
    { id: 19, lang_code: "bn", title: "বাংলা" },
    { id: 20, lang_code: "bo", title: "བོད་ཡིག" },
    { id: 21, lang_code: "br", title: "Brezhoneg" },
    { id: 22, lang_code: "bs", title: "Bosanski" },
    { id: 23, lang_code: "ca", title: "Català" },
    { id: 24, lang_code: "ce", title: "Нохчийн мотт" },
    { id: 25, lang_code: "ch", title: "Chamoru" },
    { id: 26, lang_code: "co", title: "Corsu" },
    { id: 27, lang_code: "cr", title: "ᓀᐦᐃᔭᐍᐏᐣ" },
    { id: 28, lang_code: "cs", title: "Čeština" },
    { id: 29, lang_code: "cu", title: "Словѣньскъ" },
    { id: 30, lang_code: "cv", title: "Чӑваш чӗлхи" },
    { id: 31, lang_code: "cy", title: "Cymraeg" },
    { id: 32, lang_code: "da", title: "Dansk" },
    { id: 33, lang_code: "de", title: "Deutsch" },
    { id: 34, lang_code: "dv", title: "ދިވެހި" },
    { id: 35, lang_code: "dz", title: "རྫོང་ཁ" },
    { id: 36, lang_code: "ee", title: "Eʋegbe" },
    { id: 37, lang_code: "el", title: "Ελληνικά" },
    { id: 38, lang_code: "en", title: "English" },
    { id: 39, lang_code: "eo", title: "Esperanto" },
    { id: 40, lang_code: "es", title: "Español" },
    { id: 41, lang_code: "et", title: "Eesti" },
    { id: 42, lang_code: "eu", title: "Euskara" },
    { id: 43, lang_code: "fa", title: "فارسی" },
    { id: 44, lang_code: "ff", title: "Fulfulde" },
    { id: 45, lang_code: "fi", title: "Suomi" },
    { id: 46, lang_code: "fj", title: "Vosa Vakaviti" },
    { id: 47, lang_code: "fo", title: "Føroyskt" },
    { id: 48, lang_code: "fr", title: "Français" },
    { id: 49, lang_code: "fy", title: "Frysk" },
    { id: 50, lang_code: "ga", title: "Gaeilge" },
    { id: 51, lang_code: "gd", title: "Gàidhlig" },
    { id: 52, lang_code: "gl", title: "Galego" },
    { id: 53, lang_code: "gn", title: "Avañe'ẽ" },
    { id: 54, lang_code: "gu", title: "ગુજરાતી" },
    { id: 55, lang_code: "gv", title: "Gaelg" },
    { id: 56, lang_code: "ha", title: "Hausa" },
    { id: 57, lang_code: "hi", title: "हिन्दी" },
    { id: 58, lang_code: "ho", title: "Hiri Motu" },
    { id: 59, lang_code: "hr", title: "Hrvatski" },
    { id: 60, lang_code: "ht", title: "Kreyòl ayisyen" },
    { id: 61, lang_code: "hu", title: "Magyar" },
    { id: 62, lang_code: "hy", title: "Հայերեն" },
    { id: 63, lang_code: "hz", title: "Otjiherero" },
    { id: 64, lang_code: "ia", title: "Interlingua" },
    { id: 65, lang_code: "id", title: "Bahasa Indonesia" },
    { id: 66, lang_code: "ie", title: "Interlingue" },
    { id: 67, lang_code: "ig", title: "Igbo" },
    { id: 68, lang_code: "ii", title: "ꆈꌠ꒿" },
    { id: 69, lang_code: "ik", title: "Iñupiaq" },
    { id: 70, lang_code: "io", title: "Ido" },
    { id: 71, lang_code: "is", title: "Íslenska" },
    { id: 72, lang_code: "it", title: "Italiano" },
    { id: 73, lang_code: "ja", title: "日本語" },
    { id: 74, lang_code: "jv", title: "Basa Jawa" },
    { id: 75, lang_code: "ka", title: "ქართული" },
    { id: 76, lang_code: "kg", title: "Kikongo" },
    { id: 77, lang_code: "ki", title: "Gĩkũyũ" },
    { id: 78, lang_code: "kj", title: "Kuanyama" },
    { id: 79, lang_code: "kk", title: "Қазақ тілі" },
    { id: 80, lang_code: "kl", title: "Kalaallisut" },
    { id: 81, lang_code: "km", title: "ភាសាខ្មែរ" },
    { id: 82, lang_code: "kn", title: "ಕನ್ನಡ" },
    { id: 83, lang_code: "ko", title: "한국어" },
    { id: 84, lang_code: "kr", title: "Kanuri" },
    { id: 85, lang_code: "ks", title: "कश्मीरी" },
    { id: 86, lang_code: "ku", title: "Kurdî" },
    { id: 87, lang_code: "kv", title: "Коми кыв" },
    { id: 88, lang_code: "kw", title: "Kernewek" },
    { id: 89, lang_code: "ky", title: "Кыргызча" },
    { id: 90, lang_code: "la", title: "Latina" },
    { id: 91, lang_code: "lb", title: "Lëtzebuergesch" },
    { id: 92, lang_code: "lg", title: "Luganda" },
    { id: 93, lang_code: "li", title: "Limburgs" },
    { id: 94, lang_code: "ln", title: "Lingála" },
    { id: 95, lang_code: "lo", title: "ພາສາລາວ" },
    { id: 96, lang_code: "lt", title: "Lietuvių" },
    { id: 97, lang_code: "lu", title: "Tshiluba" },
    { id: 98, lang_code: "lv", title: "Latviešu" },
    { id: 99, lang_code: "mg", title: "Malagasy" },
    { id: 100, lang_code: "mh", title: "Kajin M̧ajeļ" },
    { id: 101, lang_code: "mi", title: "Te Reo Māori" },
    { id: 102, lang_code: "mk", title: "Македонски" },
    { id: 103, lang_code: "ml", title: "മലയാളം" },
    { id: 104, lang_code: "mn", title: "Монгол" },
    { id: 105, lang_code: "mr", title: "मराठी" },
    { id: 106, lang_code: "ms", title: "Bahasa Melayu" },
    { id: 107, lang_code: "mt", title: "Malti" },
    { id: 108, lang_code: "my", title: "ဗမာစာ" },
    { id: 109, lang_code: "na", title: "Dorerin Naoero" },
    { id: 110, lang_code: "nb", title: "Norsk bokmål" },
    { id: 111, lang_code: "nd", title: "isiNdebele" },
    { id: 112, lang_code: "ne", title: "नेपाली" },
    { id: 113, lang_code: "ng", title: "Owambo" },
    { id: 114, lang_code: "nl", title: "Nederlands" },
    { id: 115, lang_code: "nn", title: "Norsk nynorsk" },
    { id: 116, lang_code: "no", title: "Norsk" },
    { id: 117, lang_code: "nr", title: "isiNdebele" },
    { id: 118, lang_code: "nv", title: "Diné bizaad" },
    { id: 119, lang_code: "ny", title: "ChiCheŵa" },
    { id: 120, lang_code: "oc", title: "Occitan" },
    { id: 121, lang_code: "oj", title: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
    { id: 122, lang_code: "om", title: "Oromoo" },
    { id: 123, lang_code: "or", title: "ଓଡ଼ିଆ" },
    { id: 124, lang_code: "os", title: "Ирон æвзаг" },
    { id: 125, lang_code: "pa", title: "ਪੰਜਾਬੀ" },
    { id: 126, lang_code: "pi", title: "पाऴि" },
    { id: 127, lang_code: "pl", title: "Polski" },
    { id: 128, lang_code: "ps", title: "پښتو" },
    { id: 129, lang_code: "pt", title: "Português" },
    { id: 130, lang_code: "qu", title: "Runa Simi" },
    { id: 131, lang_code: "rm", title: "Rumantsch" },
    { id: 132, lang_code: "rn", title: "Ikirundi" },
    { id: 133, lang_code: "ro", title: "Română" },
    { id: 134, lang_code: "ru", title: "Русский" },
    { id: 135, lang_code: "rw", title: "Ikinyarwanda" },
    { id: 136, lang_code: "sa", title: "संस्कृतम्" },
    { id: 137, lang_code: "sc", title: "Sardu" },
    { id: 138, lang_code: "sd", title: "سنڌي" },
    { id: 139, lang_code: "se", title: "Davvisámegiella" },
    { id: 140, lang_code: "sg", title: "Sängö" },
    { id: 141, lang_code: "si", title: "සිංහල" },
    { id: 142, lang_code: "sk", title: "Slovenčina" },
    { id: 143, lang_code: "sl", title: "Slovenščina" },
    { id: 144, lang_code: "sm", title: "Gagana Samoa" },
    { id: 145, lang_code: "sn", title: "chiShona" },
    { id: 146, lang_code: "so", title: "Soomaali" },
    { id: 147, lang_code: "sq", title: "Shqip" },
    { id: 148, lang_code: "sr", title: "Српски" },
    { id: 149, lang_code: "ss", title: "SiSwati" },
    { id: 150, lang_code: "st", title: "Sesotho" },
    { id: 151, lang_code: "su", title: "Basa Sunda" },
    { id: 152, lang_code: "sv", title: "Svenska" },
    { id: 153, lang_code: "sw", title: "Kiswahili" },
    { id: 154, lang_code: "ta", title: "தமிழ்" },
    { id: 155, lang_code: "te", title: "తెలుగు" },
    { id: 156, lang_code: "tg", title: "Тоҷикӣ" },
    { id: 157, lang_code: "th", title: "ไทย" },
    { id: 158, lang_code: "ti", title: "ትግርኛ" },
    { id: 159, lang_code: "tk", title: "Türkmençe" },
    { id: 160, lang_code: "tl", title: "Tagalog" },
    { id: 161, lang_code: "tn", title: "Setswana" },
    { id: 162, lang_code: "to", title: "Lea faka-Tonga" },
    { id: 163, lang_code: "tr", title: "Türkçe" },
    { id: 164, lang_code: "ts", title: "Xitsonga" },
    { id: 165, lang_code: "tt", title: "Татарча" },
    { id: 166, lang_code: "tw", title: "Twi" },
    { id: 167, lang_code: "ty", title: "Reo Tahiti" },
    { id: 168, lang_code: "ug", title: "ئۇيغۇرچە" },
    { id: 169, lang_code: "uk", title: "Українська" },
    { id: 170, lang_code: "ur", title: "اردو" },
    { id: 171, lang_code: "uz", title: "Oʻzbekcha" },
    { id: 172, lang_code: "ve", title: "Tshivenḓa" },
    { id: 173, lang_code: "vi", title: "Tiếng Việt" },
    { id: 174, lang_code: "vo", title: "Volapük" },
    { id: 175, lang_code: "wa", title: "Walon" },
    { id: 176, lang_code: "wo", title: "Wolof" },
    { id: 177, lang_code: "xh", title: "isiXhosa" },
    { id: 178, lang_code: "yi", title: "ייִדיש" },
    { id: 179, lang_code: "yo", title: "Yorùbá" },
    { id: 180, lang_code: "za", title: "Saɯ cueŋƅ" },
    { id: 181, lang_code: "zh", title: "中文" },
    { id: 182, lang_code: "zu", title: "isiZulu" },
];